// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: esp32_gui

#ifndef _ESP32_GUI_UI_H
#define _ESP32_GUI_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

void SpinAndLargen_Animation(lv_obj_t *TargetObject, int delay);
void LargeBtn_Animation(lv_obj_t *TargetObject, int delay);
void MoveColorToCenter_Animation(lv_obj_t *TargetObject, int delay);
void MoveSettingsToCenter_Animation(lv_obj_t *TargetObject, int delay);
void HideBtn_Animation(lv_obj_t *TargetObject, int delay);
void ShowBtn_Animation(lv_obj_t *TargetObject, int delay);
void up_Animation(lv_obj_t *TargetObject, int delay);
void move_up_Animation(lv_obj_t *TargetObject, int delay);
void move_down_Animation(lv_obj_t *TargetObject, int delay);
void flashscreen_Animation(lv_obj_t *TargetObject, int delay);
// SCREEN: ui_scr1
void ui_scr1_screen_init(void);
void ui_event_scr1(lv_event_t *e);
extern lv_obj_t *ui_scr1;
extern lv_obj_t *ui_CRASH_img;
extern lv_obj_t *ui_speed_panel;
extern lv_obj_t *ui_speed_bar;
extern lv_obj_t *ui_speed_num_lbl;
extern lv_obj_t *ui_km_h_lbl;
void ui_event_gesture_panel_1(lv_event_t *e);
extern lv_obj_t *ui_gesture_panel_1;
extern lv_obj_t *ui_scrolldots;
extern lv_obj_t *ui_scrolldot_1;
extern lv_obj_t *ui_scrolldot_2;
extern lv_obj_t *ui_scrolldot_3;
extern lv_obj_t *ui_scrolldot_4;
extern lv_obj_t *ui_scrolldot_21;
extern lv_obj_t *ui_content_panel_1;
extern lv_obj_t *ui_time_lbl;
extern lv_obj_t *ui_date_lbl;
extern lv_obj_t *ui_weather_info_lbl;
extern lv_obj_t *ui_temp_lbl;
extern lv_obj_t *ui_sun_img;
extern lv_obj_t *ui_moon;
extern lv_obj_t *ui_clouds;
void ui_event_gesture_panel_2(lv_event_t *e);
extern lv_obj_t *ui_gesture_panel_2;
extern lv_obj_t *ui_scrolldots1;
extern lv_obj_t *ui_scrolldot_5;
extern lv_obj_t *ui_scrolldot_6;
extern lv_obj_t *ui_scrolldot_7;
extern lv_obj_t *ui_scrolldot_8;
extern lv_obj_t *ui_scrolldot_22;
extern lv_obj_t *ui_content_panel_2;
extern lv_obj_t *ui_spotify_lbl;
extern lv_obj_t *ui_play_music_btn;
extern lv_obj_t *ui_Image6;
extern lv_obj_t *ui_play_music_btn1;
extern lv_obj_t *ui_Image20;
extern lv_obj_t *ui_play_music_btn2;
extern lv_obj_t *ui_Image19;
extern lv_obj_t *ui_notes_img;
void ui_event_gesture_panel_3(lv_event_t *e);
extern lv_obj_t *ui_gesture_panel_3;
extern lv_obj_t *ui_scrolldots2;
extern lv_obj_t *ui_scrolldot_9;
extern lv_obj_t *ui_scrolldot_10;
extern lv_obj_t *ui_scrolldot_11;
extern lv_obj_t *ui_scrolldot_12;
extern lv_obj_t *ui_scrolldot_23;
extern lv_obj_t *ui_content_panel_3;
extern lv_obj_t *ui_prox_panel;
extern lv_obj_t *ui_green_proxim_arc;
extern lv_obj_t *ui_orange_proxim_arc;
extern lv_obj_t *ui_red_proxim_arc;
extern lv_obj_t *ui_car;
extern lv_obj_t *ui_Label1;
void ui_event_gesture_panel_5(lv_event_t *e);
extern lv_obj_t *ui_gesture_panel_5;
extern lv_obj_t *ui_scrolldots4;
extern lv_obj_t *ui_scrolldot_17;
extern lv_obj_t *ui_scrolldot_18;
extern lv_obj_t *ui_scrolldot_19;
extern lv_obj_t *ui_scrolldot_20;
extern lv_obj_t *ui_scrolldot_25;
extern lv_obj_t *ui_content_panel_5;
extern lv_obj_t *ui_car2;
extern lv_obj_t *ui_door_front_right_open_bar;
extern lv_obj_t *ui_door_front_left_open_bar;
extern lv_obj_t *ui_door_back_right_open_bar;
extern lv_obj_t *ui_door_back_left_open_bar;
extern lv_obj_t *ui_door_trunk_open_bar;
void ui_event_gesture_panel_4(lv_event_t *e);
extern lv_obj_t *ui_gesture_panel_4;
extern lv_obj_t *ui_scrolldots3;
extern lv_obj_t *ui_scrolldot_13;
extern lv_obj_t *ui_scrolldot_14;
extern lv_obj_t *ui_scrolldot_15;
extern lv_obj_t *ui_scrolldot_16;
extern lv_obj_t *ui_scrolldot_24;
extern lv_obj_t *ui_content_panel_4;
extern lv_obj_t *ui_right_turn_img;
extern lv_obj_t *ui_turn_distance_lbl;
extern lv_obj_t *ui_top_time_lbl;
extern lv_obj_t *ui_top_panel;
extern lv_obj_t *ui_dummy_arc;
extern lv_obj_t *ui_fuel_green_arc;
extern lv_obj_t *ui_fuel_orange_arc;
extern lv_obj_t *ui_fuel_red_arc;
extern lv_obj_t *ui_fuel_indicator_arc1;
extern lv_obj_t *ui_fuel_icon;
extern lv_obj_t *ui_fuel_max_lbl;
extern lv_obj_t *ui_temperature_img;
extern lv_obj_t *ui_top_temp_lbl;
extern lv_obj_t *ui_humid_img;
extern lv_obj_t *ui_top_hum_lbl;
extern lv_obj_t *ui_botton_panel;
void ui_event_camera_btn(lv_event_t *e);
extern lv_obj_t *ui_camera_btn;
extern lv_obj_t *ui_camera_img;
extern lv_obj_t *ui_setting_btn;
extern lv_obj_t *ui_settings_img;
void ui_event_siren_btn(lv_event_t *e);
extern lv_obj_t *ui_siren_btn;
extern lv_obj_t *ui_play_siren_btn;
extern lv_obj_t *ui_top_date_lbl;
// SCREEN: ui_scr2
void ui_scr2_screen_init(void);
extern lv_obj_t *ui_scr2;
extern lv_obj_t *ui____initial_actions0;

LV_IMG_DECLARE(ui_img_1148992643);    // assets/bg2-min.png
LV_IMG_DECLARE(ui_img_220525951);     // assets/output-onlinepngtools-min.png
LV_IMG_DECLARE(ui_img_sun_png);       // assets/sun.png
LV_IMG_DECLARE(ui_img_497089268);     // assets/full-moon.png
LV_IMG_DECLARE(ui_img_clouds_png);    // assets/clouds.png
LV_IMG_DECLARE(ui_img_play_png);      // assets/play.png
LV_IMG_DECLARE(ui_img_forward_png);   // assets/forward.png
LV_IMG_DECLARE(ui_img_backward_png);  // assets/backward.png
LV_IMG_DECLARE(ui_img_1040270234);    // assets/music-note(2).png
LV_IMG_DECLARE(ui_img_car2_mini_png); // assets/car2_mini.png
LV_IMG_DECLARE(ui_img_1381129023);    // assets/right-turn(1).png
LV_IMG_DECLARE(ui_img_474709716);     // assets/icons8-fuel-50.png
LV_IMG_DECLARE(ui_img_temper_png);    // assets/temper.png
LV_IMG_DECLARE(ui_img_weather_1_png); // assets/weather_1.png
LV_IMG_DECLARE(ui_img_360038530);     // assets/icons8-camera-64.png
LV_IMG_DECLARE(ui_img_settings_png);  // assets/settings.png
LV_IMG_DECLARE(ui_img_weather_2_png); // assets/weather_2.png


void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
