// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: esp32_gui

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void ui_camera_btn_pressed(lv_event_t *e);
void ui_alarm_on(lv_event_t *e);
void ui_alarm_off(lv_event_t *e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
