// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: esp32_gui

#include "ui.h"
#include <stdio.h>
#include "freertos/FreeRTOS.h"
#include "freertos/queue.h"
#include "../../../main/initialization.h"


void btn_clicked(lv_event_t *e) {
    // Your code here
}

void ui_camera_btn_pressed(lv_event_t *e) {
    // Your code here
}

void ui_alarm_on(lv_event_t *e) {
    //xTaskNotifyGive(audio_task_handle);
    return;
}

void ui_alarm_off(lv_event_t *e) {
    //xTaskNotifyGive(audio_task_handle);
    return;
}
