// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: esp32_gui

#include "../ui.h"

void ui_scr1_screen_init(void) {
    ui_scr1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_scr1, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_scr1, lv_color_hex(0x191919), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_scr1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_scr1, &ui_img_1148992643, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_speed_panel = lv_obj_create(ui_scr1);
    lv_obj_set_width(ui_speed_panel, 100);
    lv_obj_set_height(ui_speed_panel, 160);
    lv_obj_set_x(ui_speed_panel, -11);
    lv_obj_set_y(ui_speed_panel, 28);
    lv_obj_set_align(ui_speed_panel, LV_ALIGN_RIGHT_MID);
    lv_obj_clear_flag(ui_speed_panel, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_radius(ui_speed_panel, 90, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_speed_panel, lv_color_hex(0x1A1A1A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_speed_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_speed_panel, lv_color_hex(0x1A1A1A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_speed_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_speed_panel, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_speed_panel, lv_color_hex(0x00FF64), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_speed_panel, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_speed_panel, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_speed_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_speed_bar = lv_bar_create(ui_speed_panel);
    lv_bar_set_range(ui_speed_bar, 0, 150);
    lv_obj_set_width(ui_speed_bar, 90);
    lv_obj_set_height(ui_speed_bar, 150);
    lv_obj_set_align(ui_speed_bar, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_speed_bar, lv_color_hex(0x333333), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_speed_bar, 150, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_speed_bar, lv_color_hex(0x00FF64), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_speed_bar, 100, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_speed_num_lbl = lv_label_create(ui_speed_bar);
    lv_obj_set_height(ui_speed_num_lbl, 65);
    lv_obj_set_width(ui_speed_num_lbl, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_speed_num_lbl, LV_ALIGN_CENTER);
    lv_label_set_text(ui_speed_num_lbl, "0");
    lv_obj_set_style_text_color(ui_speed_num_lbl, lv_color_hex(0xE6E6E6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_speed_num_lbl, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_speed_num_lbl, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_km_h_lbl = lv_label_create(ui_speed_num_lbl);
    lv_obj_set_width(ui_km_h_lbl, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_km_h_lbl, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_km_h_lbl, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_km_h_lbl, "km/h");
    lv_obj_set_style_text_font(ui_km_h_lbl, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_gesture_panel_1 = lv_obj_create(ui_scr1);
    lv_obj_set_width(ui_gesture_panel_1, 337);
    lv_obj_set_height(ui_gesture_panel_1, 190);
    lv_obj_set_x(ui_gesture_panel_1, 1);
    lv_obj_set_y(ui_gesture_panel_1, 0);
    lv_obj_set_align(ui_gesture_panel_1, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_gesture_panel_1, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_IGNORE_LAYOUT); /// Flags
    lv_obj_clear_flag(ui_gesture_panel_1,
            LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SCROLL_ELASTIC
                    | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN); /// Flags
    lv_obj_set_style_bg_color(ui_gesture_panel_1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_gesture_panel_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_gesture_panel_1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_gesture_panel_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_scrolldots = lv_obj_create(ui_gesture_panel_1);
    lv_obj_set_width(ui_scrolldots, 87);
    lv_obj_set_height(ui_scrolldots, 30);
    lv_obj_set_x(ui_scrolldots, 65);
    lv_obj_set_y(ui_scrolldots, -15);
    lv_obj_set_align(ui_scrolldots, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_clear_flag(ui_scrolldots,
            LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE
                    | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC
                    | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN); /// Flags
    lv_obj_set_scrollbar_mode(ui_scrolldots, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_bg_color(ui_scrolldots, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_scrolldots, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_scrolldots, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_scrolldots, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_scrolldot_1 = lv_obj_create(ui_scrolldots);
    lv_obj_set_width(ui_scrolldot_1, 5);
    lv_obj_set_height(ui_scrolldot_1, 5);
    lv_obj_set_align(ui_scrolldot_1, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_scrolldot_1,
            LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE
                    | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC
                    | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN); /// Flags
    lv_obj_set_style_bg_color(ui_scrolldot_1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_scrolldot_1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_scrolldot_1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_scrolldot_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_scrolldot_1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_scrolldot_1, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_color(ui_scrolldot_1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_scrolldot_1, 0, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_scrolldot_2 = lv_obj_create(ui_scrolldots);
    lv_obj_set_width(ui_scrolldot_2, 5);
    lv_obj_set_height(ui_scrolldot_2, 5);
    lv_obj_set_x(ui_scrolldot_2, 15);
    lv_obj_set_y(ui_scrolldot_2, 0);
    lv_obj_set_align(ui_scrolldot_2, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_scrolldot_2,
            LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE
                    | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC
                    | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN); /// Flags
    lv_obj_set_style_bg_color(ui_scrolldot_2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_scrolldot_2, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_scrolldot_2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_scrolldot_2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_scrolldot_2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_scrolldot_2, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_color(ui_scrolldot_2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_scrolldot_2, 0, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_scrolldot_3 = lv_obj_create(ui_scrolldots);
    lv_obj_set_width(ui_scrolldot_3, 5);
    lv_obj_set_height(ui_scrolldot_3, 5);
    lv_obj_set_x(ui_scrolldot_3, 30);
    lv_obj_set_y(ui_scrolldot_3, 0);
    lv_obj_set_align(ui_scrolldot_3, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_scrolldot_3,
            LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE
                    | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC
                    | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN); /// Flags
    lv_obj_set_style_bg_color(ui_scrolldot_3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_scrolldot_3, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_scrolldot_3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_scrolldot_3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_scrolldot_3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_scrolldot_3, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_color(ui_scrolldot_3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_scrolldot_3, 0, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_scrolldot_4 = lv_obj_create(ui_scrolldots);
    lv_obj_set_width(ui_scrolldot_4, 5);
    lv_obj_set_height(ui_scrolldot_4, 5);
    lv_obj_set_x(ui_scrolldot_4, 45);
    lv_obj_set_y(ui_scrolldot_4, 0);
    lv_obj_set_align(ui_scrolldot_4, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_scrolldot_4,
            LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE
                    | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC
                    | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN); /// Flags
    lv_obj_set_style_bg_color(ui_scrolldot_4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_scrolldot_4, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_scrolldot_4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_scrolldot_4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_scrolldot_4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_scrolldot_4, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_color(ui_scrolldot_4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_scrolldot_4, 0, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_scrolldot_21 = lv_obj_create(ui_scrolldots);
    lv_obj_set_width(ui_scrolldot_21, 5);
    lv_obj_set_height(ui_scrolldot_21, 5);
    lv_obj_set_x(ui_scrolldot_21, 60);
    lv_obj_set_y(ui_scrolldot_21, 0);
    lv_obj_set_align(ui_scrolldot_21, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_scrolldot_21,
            LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE
                    | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC
                    | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN); /// Flags
    lv_obj_set_style_bg_color(ui_scrolldot_21, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_scrolldot_21, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_scrolldot_21, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_scrolldot_21, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_scrolldot_21, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_scrolldot_21, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_color(ui_scrolldot_21, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_scrolldot_21, 0, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_content_panel_1 = lv_obj_create(ui_gesture_panel_1);
    lv_obj_set_width(ui_content_panel_1, 192);
    lv_obj_set_height(ui_content_panel_1, 152);
    lv_obj_set_x(ui_content_panel_1, -56);
    lv_obj_set_y(ui_content_panel_1, -34);
    lv_obj_set_align(ui_content_panel_1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_content_panel_1, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_content_panel_1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_content_panel_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_content_panel_1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_content_panel_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_time_lbl = lv_label_create(ui_content_panel_1);
    lv_obj_set_height(ui_time_lbl, 60);
    lv_obj_set_width(ui_time_lbl, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_time_lbl, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_time_lbl, "16:35");
    lv_obj_set_style_text_color(ui_time_lbl, lv_color_hex(0xE6E6E6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_time_lbl, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_time_lbl, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_date_lbl = lv_label_create(ui_time_lbl);
    lv_obj_set_width(ui_date_lbl, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_date_lbl, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_date_lbl, 0);
    lv_obj_set_y(ui_date_lbl, -10);
    lv_obj_set_align(ui_date_lbl, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_date_lbl, "Sat, 5 Apr");
    lv_obj_set_style_text_font(ui_date_lbl, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_clouds_img = lv_img_create(ui_content_panel_1);
    lv_img_set_src(ui_clouds_img, &ui_img_sun_rays_small_cloud_png);
    lv_obj_set_width(ui_clouds_img, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_clouds_img, LV_SIZE_CONTENT); /// 48
    lv_obj_set_x(ui_clouds_img, -54);
    lv_obj_set_y(ui_clouds_img, 22);
    lv_obj_set_align(ui_clouds_img, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_clouds_img, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    lv_obj_clear_flag(ui_clouds_img, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_weather_info_lbl = lv_label_create(ui_content_panel_1);
    lv_obj_set_width(ui_weather_info_lbl, 100);
    lv_obj_set_height(ui_weather_info_lbl, LV_SIZE_CONTENT); /// 10
    lv_obj_set_x(ui_weather_info_lbl, 17);
    lv_obj_set_y(ui_weather_info_lbl, 15);
    lv_obj_set_align(ui_weather_info_lbl, LV_ALIGN_CENTER);
    lv_label_set_text(ui_weather_info_lbl, "Partly cloudy");
    lv_obj_set_style_text_color(ui_weather_info_lbl, lv_color_hex(0xE6E6E6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_weather_info_lbl, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_weather_info_lbl, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_temp_lbl = lv_label_create(ui_content_panel_1);
    lv_obj_set_width(ui_temp_lbl, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_temp_lbl, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_temp_lbl, -13);
    lv_obj_set_y(ui_temp_lbl, 34);
    lv_obj_set_align(ui_temp_lbl, LV_ALIGN_CENTER);
    lv_label_set_text(ui_temp_lbl, "21°C");
    lv_obj_set_style_text_color(ui_temp_lbl, lv_color_hex(0xE6E6E6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_temp_lbl, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_gesture_panel_2 = lv_obj_create(ui_scr1);
    lv_obj_set_width(ui_gesture_panel_2, 337);
    lv_obj_set_height(ui_gesture_panel_2, 191);
    lv_obj_set_x(ui_gesture_panel_2, 1);
    lv_obj_set_y(ui_gesture_panel_2, 0);
    lv_obj_set_align(ui_gesture_panel_2, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_gesture_panel_2, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_IGNORE_LAYOUT); /// Flags
    lv_obj_clear_flag(ui_gesture_panel_2,
            LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SCROLL_ELASTIC
                    | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN); /// Flags
    lv_obj_set_style_bg_color(ui_gesture_panel_2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_gesture_panel_2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_gesture_panel_2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_gesture_panel_2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_scrolldots1 = lv_obj_create(ui_gesture_panel_2);
    lv_obj_set_width(ui_scrolldots1, 91);
    lv_obj_set_height(ui_scrolldots1, 30);
    lv_obj_set_x(ui_scrolldots1, 65);
    lv_obj_set_y(ui_scrolldots1, -15);
    lv_obj_set_align(ui_scrolldots1, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_clear_flag(ui_scrolldots1,
            LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE
                    | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC
                    | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN); /// Flags
    lv_obj_set_scrollbar_mode(ui_scrolldots1, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_bg_color(ui_scrolldots1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_scrolldots1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_scrolldots1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_scrolldots1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_scrolldot_5 = lv_obj_create(ui_scrolldots1);
    lv_obj_set_width(ui_scrolldot_5, 5);
    lv_obj_set_height(ui_scrolldot_5, 5);
    lv_obj_set_align(ui_scrolldot_5, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_scrolldot_5,
            LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE
                    | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC
                    | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN); /// Flags
    lv_obj_set_style_bg_color(ui_scrolldot_5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_scrolldot_5, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_scrolldot_5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_scrolldot_5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_scrolldot_5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_scrolldot_5, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_color(ui_scrolldot_5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_scrolldot_5, 0, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_scrolldot_6 = lv_obj_create(ui_scrolldots1);
    lv_obj_set_width(ui_scrolldot_6, 5);
    lv_obj_set_height(ui_scrolldot_6, 5);
    lv_obj_set_x(ui_scrolldot_6, 15);
    lv_obj_set_y(ui_scrolldot_6, 0);
    lv_obj_set_align(ui_scrolldot_6, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_scrolldot_6,
            LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE
                    | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC
                    | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN); /// Flags
    lv_obj_set_style_bg_color(ui_scrolldot_6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_scrolldot_6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_scrolldot_6, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_scrolldot_6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_scrolldot_6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_scrolldot_6, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_color(ui_scrolldot_6, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_scrolldot_6, 0, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_scrolldot_7 = lv_obj_create(ui_scrolldots1);
    lv_obj_set_width(ui_scrolldot_7, 5);
    lv_obj_set_height(ui_scrolldot_7, 5);
    lv_obj_set_x(ui_scrolldot_7, 30);
    lv_obj_set_y(ui_scrolldot_7, 0);
    lv_obj_set_align(ui_scrolldot_7, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_scrolldot_7,
            LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE
                    | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC
                    | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN); /// Flags
    lv_obj_set_style_bg_color(ui_scrolldot_7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_scrolldot_7, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_scrolldot_7, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_scrolldot_7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_scrolldot_7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_scrolldot_7, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_color(ui_scrolldot_7, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_scrolldot_7, 0, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_scrolldot_8 = lv_obj_create(ui_scrolldots1);
    lv_obj_set_width(ui_scrolldot_8, 5);
    lv_obj_set_height(ui_scrolldot_8, 5);
    lv_obj_set_x(ui_scrolldot_8, 45);
    lv_obj_set_y(ui_scrolldot_8, 0);
    lv_obj_set_align(ui_scrolldot_8, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_scrolldot_8,
            LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE
                    | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC
                    | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN); /// Flags
    lv_obj_set_style_bg_color(ui_scrolldot_8, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_scrolldot_8, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_scrolldot_8, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_scrolldot_8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_scrolldot_8, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_scrolldot_8, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_color(ui_scrolldot_8, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_scrolldot_8, 0, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_scrolldot_22 = lv_obj_create(ui_scrolldots1);
    lv_obj_set_width(ui_scrolldot_22, 5);
    lv_obj_set_height(ui_scrolldot_22, 5);
    lv_obj_set_x(ui_scrolldot_22, 60);
    lv_obj_set_y(ui_scrolldot_22, 0);
    lv_obj_set_align(ui_scrolldot_22, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_scrolldot_22,
            LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE
                    | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC
                    | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN); /// Flags
    lv_obj_set_style_bg_color(ui_scrolldot_22, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_scrolldot_22, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_scrolldot_22, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_scrolldot_22, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_scrolldot_22, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_scrolldot_22, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_color(ui_scrolldot_22, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_scrolldot_22, 0, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_content_panel_2 = lv_obj_create(ui_gesture_panel_2);
    lv_obj_set_width(ui_content_panel_2, 192);
    lv_obj_set_height(ui_content_panel_2, 152);
    lv_obj_set_x(ui_content_panel_2, -56);
    lv_obj_set_y(ui_content_panel_2, -34);
    lv_obj_set_align(ui_content_panel_2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_content_panel_2, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_content_panel_2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_content_panel_2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_content_panel_2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_content_panel_2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_music_note_img = lv_img_create(ui_content_panel_2);
    lv_img_set_src(ui_music_note_img, &ui_img_1040273307);
    lv_obj_set_width(ui_music_note_img, LV_SIZE_CONTENT);  /// 64
    lv_obj_set_height(ui_music_note_img, LV_SIZE_CONTENT); /// 64
    lv_obj_set_x(ui_music_note_img, -53);
    lv_obj_set_y(ui_music_note_img, -36);
    lv_obj_set_align(ui_music_note_img, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_music_note_img, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    lv_obj_clear_flag(ui_music_note_img, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_img_set_zoom(ui_music_note_img, 200);

    ui_spotify_lbl = lv_label_create(ui_content_panel_2);
    lv_obj_set_height(ui_spotify_lbl, 18);
    lv_obj_set_width(ui_spotify_lbl, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_spotify_lbl, 2);
    lv_obj_set_y(ui_spotify_lbl, 52);
    lv_obj_set_align(ui_spotify_lbl, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_spotify_lbl, "Najbolja pisma ikad");
    lv_obj_set_style_text_color(ui_spotify_lbl, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_spotify_lbl, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_spotify_lbl, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_play_music_btn = lv_btn_create(ui_content_panel_2);
    lv_obj_set_width(ui_play_music_btn, 50);
    lv_obj_set_height(ui_play_music_btn, 50);
    lv_obj_set_x(ui_play_music_btn, 0);
    lv_obj_set_y(ui_play_music_btn, 5);
    lv_obj_set_align(ui_play_music_btn, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_play_music_btn, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
    lv_obj_clear_flag(ui_play_music_btn, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_SCROLLABLE);   /// Flags
    lv_obj_set_style_radius(ui_play_music_btn, 90, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_play_music_btn, lv_color_hex(0x00EED5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_play_music_btn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_play_music_btn, lv_color_hex(0xFD8501), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_play_music_btn, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_color(ui_play_music_btn, lv_color_hex(0xFF8804), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_play_music_btn, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Image6 = lv_img_create(ui_play_music_btn);
    lv_img_set_src(ui_Image6, &ui_img_play_png);
    lv_obj_set_width(ui_Image6, LV_SIZE_CONTENT);  /// 18
    lv_obj_set_height(ui_Image6, LV_SIZE_CONTENT); /// 22
    lv_obj_set_x(ui_Image6, 2);
    lv_obj_set_y(ui_Image6, 0);
    lv_obj_set_align(ui_Image6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image6, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    lv_obj_clear_flag(ui_Image6, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_previous_btn = lv_imgbtn_create(ui_content_panel_2);
    lv_imgbtn_set_src(ui_previous_btn, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_backward_png, NULL);
    lv_obj_set_height(ui_previous_btn, 20);
    lv_obj_set_width(ui_previous_btn, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_previous_btn, -50);
    lv_obj_set_y(ui_previous_btn, 42);
    lv_obj_set_align(ui_previous_btn, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_img_src(ui_previous_btn, &ui_img_backward_png, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_forward_btn = lv_imgbtn_create(ui_content_panel_2);
    lv_imgbtn_set_src(ui_forward_btn, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_forward_png, NULL);
    lv_obj_set_height(ui_forward_btn, 20);
    lv_obj_set_width(ui_forward_btn, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_forward_btn, 50);
    lv_obj_set_y(ui_forward_btn, 42);
    lv_obj_set_align(ui_forward_btn, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_forward_btn, LV_OBJ_FLAG_PRESS_LOCK); /// Flags
    lv_obj_set_style_bg_img_src(ui_forward_btn, &ui_img_forward_png, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_gesture_panel_3 = lv_obj_create(ui_scr1);
    lv_obj_set_width(ui_gesture_panel_3, 337);
    lv_obj_set_height(ui_gesture_panel_3, 191);
    lv_obj_set_x(ui_gesture_panel_3, 1);
    lv_obj_set_y(ui_gesture_panel_3, 0);
    lv_obj_set_align(ui_gesture_panel_3, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_gesture_panel_3, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_IGNORE_LAYOUT); /// Flags
    lv_obj_clear_flag(ui_gesture_panel_3,
            LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SCROLL_ELASTIC
                    | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN); /// Flags
    lv_obj_set_style_bg_color(ui_gesture_panel_3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_gesture_panel_3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_gesture_panel_3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_gesture_panel_3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_scrolldots2 = lv_obj_create(ui_gesture_panel_3);
    lv_obj_set_width(ui_scrolldots2, 93);
    lv_obj_set_height(ui_scrolldots2, 30);
    lv_obj_set_x(ui_scrolldots2, 65);
    lv_obj_set_y(ui_scrolldots2, -15);
    lv_obj_set_align(ui_scrolldots2, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_clear_flag(ui_scrolldots2,
            LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE
                    | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC
                    | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN); /// Flags
    lv_obj_set_scrollbar_mode(ui_scrolldots2, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_bg_color(ui_scrolldots2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_scrolldots2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_scrolldots2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_scrolldots2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_scrolldot_9 = lv_obj_create(ui_scrolldots2);
    lv_obj_set_width(ui_scrolldot_9, 5);
    lv_obj_set_height(ui_scrolldot_9, 5);
    lv_obj_set_align(ui_scrolldot_9, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_scrolldot_9,
            LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE
                    | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC
                    | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN); /// Flags
    lv_obj_set_style_bg_color(ui_scrolldot_9, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_scrolldot_9, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_scrolldot_9, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_scrolldot_9, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_scrolldot_9, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_scrolldot_9, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_color(ui_scrolldot_9, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_scrolldot_9, 0, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_scrolldot_10 = lv_obj_create(ui_scrolldots2);
    lv_obj_set_width(ui_scrolldot_10, 5);
    lv_obj_set_height(ui_scrolldot_10, 5);
    lv_obj_set_x(ui_scrolldot_10, 15);
    lv_obj_set_y(ui_scrolldot_10, 0);
    lv_obj_set_align(ui_scrolldot_10, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_scrolldot_10,
            LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE
                    | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC
                    | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN); /// Flags
    lv_obj_set_style_bg_color(ui_scrolldot_10, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_scrolldot_10, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_scrolldot_10, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_scrolldot_10, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_scrolldot_10, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_scrolldot_10, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_color(ui_scrolldot_10, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_scrolldot_10, 0, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_scrolldot_11 = lv_obj_create(ui_scrolldots2);
    lv_obj_set_width(ui_scrolldot_11, 5);
    lv_obj_set_height(ui_scrolldot_11, 5);
    lv_obj_set_x(ui_scrolldot_11, 30);
    lv_obj_set_y(ui_scrolldot_11, 0);
    lv_obj_set_align(ui_scrolldot_11, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_scrolldot_11,
            LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE
                    | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC
                    | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN); /// Flags
    lv_obj_set_style_bg_color(ui_scrolldot_11, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_scrolldot_11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_scrolldot_11, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_scrolldot_11, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_scrolldot_11, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_scrolldot_11, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_color(ui_scrolldot_11, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_scrolldot_11, 0, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_scrolldot_12 = lv_obj_create(ui_scrolldots2);
    lv_obj_set_width(ui_scrolldot_12, 5);
    lv_obj_set_height(ui_scrolldot_12, 5);
    lv_obj_set_x(ui_scrolldot_12, 45);
    lv_obj_set_y(ui_scrolldot_12, 0);
    lv_obj_set_align(ui_scrolldot_12, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_scrolldot_12,
            LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE
                    | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC
                    | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN); /// Flags
    lv_obj_set_style_bg_color(ui_scrolldot_12, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_scrolldot_12, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_scrolldot_12, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_scrolldot_12, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_scrolldot_12, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_scrolldot_12, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_color(ui_scrolldot_12, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_scrolldot_12, 0, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_scrolldot_23 = lv_obj_create(ui_scrolldots2);
    lv_obj_set_width(ui_scrolldot_23, 5);
    lv_obj_set_height(ui_scrolldot_23, 5);
    lv_obj_set_x(ui_scrolldot_23, 60);
    lv_obj_set_y(ui_scrolldot_23, 0);
    lv_obj_set_align(ui_scrolldot_23, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_scrolldot_23,
            LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE
                    | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC
                    | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN); /// Flags
    lv_obj_set_style_bg_color(ui_scrolldot_23, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_scrolldot_23, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_scrolldot_23, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_scrolldot_23, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_scrolldot_23, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_scrolldot_23, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_color(ui_scrolldot_23, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_scrolldot_23, 0, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_content_panel_3 = lv_obj_create(ui_gesture_panel_3);
    lv_obj_set_width(ui_content_panel_3, 203);
    lv_obj_set_height(ui_content_panel_3, 152);
    lv_obj_set_x(ui_content_panel_3, -56);
    lv_obj_set_y(ui_content_panel_3, -32);
    lv_obj_set_align(ui_content_panel_3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_content_panel_3, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_content_panel_3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_content_panel_3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_content_panel_3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_content_panel_3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_prox_panel = lv_obj_create(ui_content_panel_3);
    lv_obj_set_width(ui_prox_panel, 204);
    lv_obj_set_height(ui_prox_panel, 50);
    lv_obj_set_x(ui_prox_panel, 0);
    lv_obj_set_y(ui_prox_panel, 15);
    lv_obj_set_align(ui_prox_panel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_prox_panel, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_prox_panel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_prox_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_prox_panel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_prox_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_green_proxim_arc = lv_arc_create(ui_prox_panel);
    lv_obj_set_width(ui_green_proxim_arc, 190);
    lv_obj_set_height(ui_green_proxim_arc, 190);
    lv_obj_set_align(ui_green_proxim_arc, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_green_proxim_arc,
            LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE
                    | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC
                    | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN); /// Flags
    lv_arc_set_value(ui_green_proxim_arc, 50);
    lv_arc_set_mode(ui_green_proxim_arc, LV_ARC_MODE_SYMMETRICAL);
    lv_obj_set_style_bg_color(ui_green_proxim_arc, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_green_proxim_arc, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(ui_green_proxim_arc, lv_color_hex(0x4040FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_green_proxim_arc, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_green_proxim_arc, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_green_proxim_arc, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_green_proxim_arc, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(ui_green_proxim_arc, lv_color_hex(0x00FF64), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_green_proxim_arc, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_green_proxim_arc, 5, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_green_proxim_arc, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_green_proxim_arc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_orange_proxim_arc = lv_arc_create(ui_prox_panel);
    lv_obj_set_width(ui_orange_proxim_arc, 170);
    lv_obj_set_height(ui_orange_proxim_arc, 170);
    lv_obj_set_align(ui_orange_proxim_arc, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_orange_proxim_arc,
            LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE
                    | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC
                    | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN); /// Flags
    lv_arc_set_value(ui_orange_proxim_arc, 50);
    lv_arc_set_mode(ui_orange_proxim_arc, LV_ARC_MODE_SYMMETRICAL);
    lv_obj_set_style_arc_color(ui_orange_proxim_arc, lv_color_hex(0x4040FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_orange_proxim_arc, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_orange_proxim_arc, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_orange_proxim_arc, lv_color_hex(0xFF9900), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_orange_proxim_arc, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_orange_proxim_arc, 5, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_red_proxim_arc = lv_arc_create(ui_prox_panel);
    lv_obj_set_width(ui_red_proxim_arc, 150);
    lv_obj_set_height(ui_red_proxim_arc, 150);
    lv_obj_set_align(ui_red_proxim_arc, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_red_proxim_arc,
            LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE
                    | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC
                    | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN); /// Flags
    lv_arc_set_value(ui_red_proxim_arc, 50);
    lv_arc_set_mode(ui_red_proxim_arc, LV_ARC_MODE_SYMMETRICAL);
    lv_obj_set_style_arc_color(ui_red_proxim_arc, lv_color_hex(0x4040FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_red_proxim_arc, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_red_proxim_arc, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_red_proxim_arc, lv_color_hex(0xFF0000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_red_proxim_arc, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_red_proxim_arc, 5, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_car = lv_img_create(ui_prox_panel);
    lv_img_set_src(ui_car, &ui_img_car2_mini_png);
    lv_obj_set_width(ui_car, LV_SIZE_CONTENT);  /// 150
    lv_obj_set_height(ui_car, LV_SIZE_CONTENT); /// 150
    lv_obj_set_x(ui_car, -1);
    lv_obj_set_y(ui_car, -2);
    lv_obj_set_align(ui_car, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_car, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    lv_obj_clear_flag(ui_car, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_img_set_angle(ui_car, 900);
    lv_img_set_zoom(ui_car, 220);

    ui_gesture_panel_5 = lv_obj_create(ui_scr1);
    lv_obj_set_width(ui_gesture_panel_5, 337);
    lv_obj_set_height(ui_gesture_panel_5, 191);
    lv_obj_set_x(ui_gesture_panel_5, 1);
    lv_obj_set_y(ui_gesture_panel_5, 0);
    lv_obj_set_align(ui_gesture_panel_5, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_gesture_panel_5, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_IGNORE_LAYOUT); /// Flags
    lv_obj_clear_flag(ui_gesture_panel_5,
            LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SCROLL_ELASTIC
                    | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN); /// Flags
    lv_obj_set_style_bg_color(ui_gesture_panel_5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_gesture_panel_5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_gesture_panel_5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_gesture_panel_5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_scrolldots4 = lv_obj_create(ui_gesture_panel_5);
    lv_obj_set_width(ui_scrolldots4, 90);
    lv_obj_set_height(ui_scrolldots4, 30);
    lv_obj_set_x(ui_scrolldots4, 65);
    lv_obj_set_y(ui_scrolldots4, -15);
    lv_obj_set_align(ui_scrolldots4, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_clear_flag(ui_scrolldots4,
            LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE
                    | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC
                    | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN); /// Flags
    lv_obj_set_scrollbar_mode(ui_scrolldots4, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_bg_color(ui_scrolldots4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_scrolldots4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_scrolldots4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_scrolldots4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_scrolldot_17 = lv_obj_create(ui_scrolldots4);
    lv_obj_set_width(ui_scrolldot_17, 5);
    lv_obj_set_height(ui_scrolldot_17, 5);
    lv_obj_set_align(ui_scrolldot_17, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_scrolldot_17,
            LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE
                    | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC
                    | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN); /// Flags
    lv_obj_set_style_bg_color(ui_scrolldot_17, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_scrolldot_17, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_scrolldot_17, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_scrolldot_17, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_scrolldot_17, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_scrolldot_17, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_color(ui_scrolldot_17, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_scrolldot_17, 0, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_scrolldot_18 = lv_obj_create(ui_scrolldots4);
    lv_obj_set_width(ui_scrolldot_18, 5);
    lv_obj_set_height(ui_scrolldot_18, 5);
    lv_obj_set_x(ui_scrolldot_18, 15);
    lv_obj_set_y(ui_scrolldot_18, 0);
    lv_obj_set_align(ui_scrolldot_18, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_scrolldot_18,
            LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE
                    | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC
                    | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN); /// Flags
    lv_obj_set_style_bg_color(ui_scrolldot_18, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_scrolldot_18, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_scrolldot_18, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_scrolldot_18, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_scrolldot_18, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_scrolldot_18, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_color(ui_scrolldot_18, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_scrolldot_18, 0, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_scrolldot_19 = lv_obj_create(ui_scrolldots4);
    lv_obj_set_width(ui_scrolldot_19, 5);
    lv_obj_set_height(ui_scrolldot_19, 5);
    lv_obj_set_x(ui_scrolldot_19, 30);
    lv_obj_set_y(ui_scrolldot_19, 0);
    lv_obj_set_align(ui_scrolldot_19, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_scrolldot_19,
            LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE
                    | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC
                    | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN); /// Flags
    lv_obj_set_style_bg_color(ui_scrolldot_19, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_scrolldot_19, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_scrolldot_19, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_scrolldot_19, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_scrolldot_19, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_scrolldot_19, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_color(ui_scrolldot_19, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_scrolldot_19, 0, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_scrolldot_20 = lv_obj_create(ui_scrolldots4);
    lv_obj_set_width(ui_scrolldot_20, 5);
    lv_obj_set_height(ui_scrolldot_20, 5);
    lv_obj_set_x(ui_scrolldot_20, 45);
    lv_obj_set_y(ui_scrolldot_20, 0);
    lv_obj_set_align(ui_scrolldot_20, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_scrolldot_20,
            LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE
                    | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC
                    | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN); /// Flags
    lv_obj_set_style_bg_color(ui_scrolldot_20, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_scrolldot_20, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_scrolldot_20, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_scrolldot_20, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_scrolldot_20, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_scrolldot_20, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_color(ui_scrolldot_20, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_scrolldot_20, 0, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_scrolldot_25 = lv_obj_create(ui_scrolldots4);
    lv_obj_set_width(ui_scrolldot_25, 5);
    lv_obj_set_height(ui_scrolldot_25, 5);
    lv_obj_set_x(ui_scrolldot_25, 60);
    lv_obj_set_y(ui_scrolldot_25, 0);
    lv_obj_set_align(ui_scrolldot_25, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_scrolldot_25,
            LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE
                    | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC
                    | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN); /// Flags
    lv_obj_set_style_bg_color(ui_scrolldot_25, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_scrolldot_25, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_scrolldot_25, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_scrolldot_25, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_scrolldot_25, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_scrolldot_25, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_color(ui_scrolldot_25, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_scrolldot_25, 0, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_content_panel_5 = lv_obj_create(ui_gesture_panel_5);
    lv_obj_set_width(ui_content_panel_5, 151);
    lv_obj_set_height(ui_content_panel_5, 114);
    lv_obj_set_x(ui_content_panel_5, -51);
    lv_obj_set_y(ui_content_panel_5, -22);
    lv_obj_set_align(ui_content_panel_5, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_content_panel_5, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_content_panel_5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_content_panel_5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_content_panel_5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_content_panel_5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_car2 = lv_img_create(ui_content_panel_5);
    lv_img_set_src(ui_car2, &ui_img_car2_mini_png);
    lv_obj_set_width(ui_car2, LV_SIZE_CONTENT);  /// 150
    lv_obj_set_height(ui_car2, LV_SIZE_CONTENT); /// 150
    lv_obj_set_x(ui_car2, -6);
    lv_obj_set_y(ui_car2, 3);
    lv_obj_set_align(ui_car2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_car2, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    lv_obj_clear_flag(ui_car2, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_img_set_angle(ui_car2, 900);
    lv_img_set_zoom(ui_car2, 220);

    ui_door_front_right_open_bar = lv_bar_create(ui_content_panel_5);
    lv_bar_set_value(ui_door_front_right_open_bar, 100, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_door_front_right_open_bar, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_door_front_right_open_bar, 26);
    lv_obj_set_height(ui_door_front_right_open_bar, 10);
    lv_obj_set_x(ui_door_front_right_open_bar, -12);
    lv_obj_set_y(ui_door_front_right_open_bar, -27);
    lv_obj_set_align(ui_door_front_right_open_bar, LV_ALIGN_CENTER);

    lv_obj_set_style_bg_color(ui_door_front_right_open_bar, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_door_front_right_open_bar, 180, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_door_front_right_open_bar, lv_color_hex(0xFF0000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_door_front_right_open_bar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_door_front_right_open_bar, 3, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_door_front_right_open_bar, LV_BORDER_SIDE_TOP, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_door_front_left_open_bar = lv_bar_create(ui_content_panel_5);
    lv_bar_set_value(ui_door_front_left_open_bar, 100, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_door_front_left_open_bar, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_door_front_left_open_bar, 26);
    lv_obj_set_height(ui_door_front_left_open_bar, 10);
    lv_obj_set_x(ui_door_front_left_open_bar, -12);
    lv_obj_set_y(ui_door_front_left_open_bar, 32);
    lv_obj_set_align(ui_door_front_left_open_bar, LV_ALIGN_CENTER);

    lv_obj_set_style_bg_color(ui_door_front_left_open_bar, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_door_front_left_open_bar, 180, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_door_front_left_open_bar, lv_color_hex(0xFF0000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_door_front_left_open_bar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_door_front_left_open_bar, 3, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_door_front_left_open_bar, LV_BORDER_SIDE_BOTTOM, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_door_back_right_open_bar = lv_bar_create(ui_content_panel_5);
    lv_bar_set_value(ui_door_back_right_open_bar, 100, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_door_back_right_open_bar, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_door_back_right_open_bar, 26);
    lv_obj_set_height(ui_door_back_right_open_bar, 10);
    lv_obj_set_x(ui_door_back_right_open_bar, 19);
    lv_obj_set_y(ui_door_back_right_open_bar, -27);
    lv_obj_set_align(ui_door_back_right_open_bar, LV_ALIGN_CENTER);

    lv_obj_set_style_bg_color(ui_door_back_right_open_bar, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_door_back_right_open_bar, 180, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_door_back_right_open_bar, lv_color_hex(0xFF0000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_door_back_right_open_bar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_door_back_right_open_bar, 3, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_door_back_right_open_bar, LV_BORDER_SIDE_TOP, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_door_back_left_open_bar = lv_bar_create(ui_content_panel_5);
    lv_bar_set_value(ui_door_back_left_open_bar, 100, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_door_back_left_open_bar, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_door_back_left_open_bar, 26);
    lv_obj_set_height(ui_door_back_left_open_bar, 10);
    lv_obj_set_x(ui_door_back_left_open_bar, 19);
    lv_obj_set_y(ui_door_back_left_open_bar, 32);
    lv_obj_set_align(ui_door_back_left_open_bar, LV_ALIGN_CENTER);

    lv_obj_set_style_bg_color(ui_door_back_left_open_bar, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_door_back_left_open_bar, 180, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_door_back_left_open_bar, lv_color_hex(0xFF0000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_door_back_left_open_bar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_door_back_left_open_bar, 3, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_door_back_left_open_bar, LV_BORDER_SIDE_BOTTOM, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_door_trunk_open_bar = lv_bar_create(ui_content_panel_5);
    lv_bar_set_value(ui_door_trunk_open_bar, 100, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_door_trunk_open_bar, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_door_trunk_open_bar, 10);
    lv_obj_set_height(ui_door_trunk_open_bar, 35);
    lv_obj_set_x(ui_door_trunk_open_bar, 64);
    lv_obj_set_y(ui_door_trunk_open_bar, 4);
    lv_obj_set_align(ui_door_trunk_open_bar, LV_ALIGN_CENTER);

    lv_obj_set_style_bg_color(ui_door_trunk_open_bar, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_door_trunk_open_bar, 180, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_door_trunk_open_bar, lv_color_hex(0xFF0000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_door_trunk_open_bar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_door_trunk_open_bar, 3, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_door_trunk_open_bar, LV_BORDER_SIDE_RIGHT, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_gesture_panel_4 = lv_obj_create(ui_scr1);
    lv_obj_set_width(ui_gesture_panel_4, 337);
    lv_obj_set_height(ui_gesture_panel_4, 191);
    lv_obj_set_x(ui_gesture_panel_4, 1);
    lv_obj_set_y(ui_gesture_panel_4, 0);
    lv_obj_set_align(ui_gesture_panel_4, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_gesture_panel_4, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_IGNORE_LAYOUT); /// Flags
    lv_obj_clear_flag(ui_gesture_panel_4,
            LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SCROLL_ELASTIC
                    | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN); /// Flags
    lv_obj_set_style_bg_color(ui_gesture_panel_4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_gesture_panel_4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_gesture_panel_4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_gesture_panel_4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_scrolldots3 = lv_obj_create(ui_gesture_panel_4);
    lv_obj_set_width(ui_scrolldots3, 92);
    lv_obj_set_height(ui_scrolldots3, 30);
    lv_obj_set_x(ui_scrolldots3, 65);
    lv_obj_set_y(ui_scrolldots3, -15);
    lv_obj_set_align(ui_scrolldots3, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_clear_flag(ui_scrolldots3,
            LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE
                    | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC
                    | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN); /// Flags
    lv_obj_set_scrollbar_mode(ui_scrolldots3, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_bg_color(ui_scrolldots3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_scrolldots3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_scrolldots3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_scrolldots3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_scrolldot_13 = lv_obj_create(ui_scrolldots3);
    lv_obj_set_width(ui_scrolldot_13, 5);
    lv_obj_set_height(ui_scrolldot_13, 5);
    lv_obj_set_align(ui_scrolldot_13, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_scrolldot_13,
            LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE
                    | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC
                    | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN); /// Flags
    lv_obj_set_style_bg_color(ui_scrolldot_13, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_scrolldot_13, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_scrolldot_13, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_scrolldot_13, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_scrolldot_13, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_scrolldot_13, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_color(ui_scrolldot_13, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_scrolldot_13, 0, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_scrolldot_14 = lv_obj_create(ui_scrolldots3);
    lv_obj_set_width(ui_scrolldot_14, 5);
    lv_obj_set_height(ui_scrolldot_14, 5);
    lv_obj_set_x(ui_scrolldot_14, 15);
    lv_obj_set_y(ui_scrolldot_14, 0);
    lv_obj_set_align(ui_scrolldot_14, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_scrolldot_14,
            LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE
                    | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC
                    | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN); /// Flags
    lv_obj_set_style_bg_color(ui_scrolldot_14, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_scrolldot_14, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_scrolldot_14, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_scrolldot_14, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_scrolldot_14, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_scrolldot_14, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_color(ui_scrolldot_14, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_scrolldot_14, 0, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_scrolldot_15 = lv_obj_create(ui_scrolldots3);
    lv_obj_set_width(ui_scrolldot_15, 5);
    lv_obj_set_height(ui_scrolldot_15, 5);
    lv_obj_set_x(ui_scrolldot_15, 30);
    lv_obj_set_y(ui_scrolldot_15, 0);
    lv_obj_set_align(ui_scrolldot_15, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_scrolldot_15,
            LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE
                    | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC
                    | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN); /// Flags
    lv_obj_set_style_bg_color(ui_scrolldot_15, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_scrolldot_15, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_scrolldot_15, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_scrolldot_15, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_scrolldot_15, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_scrolldot_15, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_color(ui_scrolldot_15, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_scrolldot_15, 0, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_scrolldot_16 = lv_obj_create(ui_scrolldots3);
    lv_obj_set_width(ui_scrolldot_16, 5);
    lv_obj_set_height(ui_scrolldot_16, 5);
    lv_obj_set_x(ui_scrolldot_16, 45);
    lv_obj_set_y(ui_scrolldot_16, 0);
    lv_obj_set_align(ui_scrolldot_16, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_scrolldot_16,
            LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE
                    | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC
                    | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN); /// Flags
    lv_obj_set_style_bg_color(ui_scrolldot_16, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_scrolldot_16, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_scrolldot_16, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_scrolldot_16, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_scrolldot_16, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_scrolldot_16, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_color(ui_scrolldot_16, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_scrolldot_16, 0, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_scrolldot_24 = lv_obj_create(ui_scrolldots3);
    lv_obj_set_width(ui_scrolldot_24, 5);
    lv_obj_set_height(ui_scrolldot_24, 5);
    lv_obj_set_x(ui_scrolldot_24, 60);
    lv_obj_set_y(ui_scrolldot_24, 0);
    lv_obj_set_align(ui_scrolldot_24, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_scrolldot_24,
            LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE
                    | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC
                    | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN); /// Flags
    lv_obj_set_style_bg_color(ui_scrolldot_24, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_scrolldot_24, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_scrolldot_24, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_scrolldot_24, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_scrolldot_24, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_scrolldot_24, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_color(ui_scrolldot_24, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_scrolldot_24, 0, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_content_panel_4 = lv_obj_create(ui_gesture_panel_4);
    lv_obj_set_width(ui_content_panel_4, 192);
    lv_obj_set_height(ui_content_panel_4, 152);
    lv_obj_set_x(ui_content_panel_4, -56);
    lv_obj_set_y(ui_content_panel_4, -34);
    lv_obj_set_align(ui_content_panel_4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_content_panel_4, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_content_panel_4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_content_panel_4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_content_panel_4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_content_panel_4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_navigation_lbl = lv_label_create(ui_content_panel_4);
    lv_obj_set_height(ui_navigation_lbl, 128);
    lv_obj_set_width(ui_navigation_lbl, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_navigation_lbl, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_navigation_lbl, "<---.\n      |\n      |");
    lv_obj_set_style_text_color(ui_navigation_lbl, lv_color_hex(0xCCCCCC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_navigation_lbl, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_navigation_lbl, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_top_time_lbl = lv_label_create(ui_scr1);
    lv_obj_set_width(ui_top_time_lbl, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_top_time_lbl, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_top_time_lbl, 138);
    lv_obj_set_y(ui_top_time_lbl, -106);
    lv_obj_set_align(ui_top_time_lbl, LV_ALIGN_CENTER);
    lv_label_set_text(ui_top_time_lbl, "16:35");
    lv_obj_add_flag(ui_top_time_lbl, LV_OBJ_FLAG_HIDDEN); /// Flags
    lv_obj_set_style_text_color(ui_top_time_lbl, lv_color_hex(0xE6E6E6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_top_time_lbl, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_top_date_lbl = lv_label_create(ui_scr1);
    lv_obj_set_width(ui_top_date_lbl, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_top_date_lbl, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_top_date_lbl, 80);
    lv_obj_set_y(ui_top_date_lbl, -106);
    lv_obj_set_align(ui_top_date_lbl, LV_ALIGN_CENTER);
    lv_label_set_text(ui_top_date_lbl, "Sat, 5 Apr");
    lv_obj_add_flag(ui_top_date_lbl, LV_OBJ_FLAG_HIDDEN); /// Flags
    lv_obj_set_style_text_color(ui_top_date_lbl, lv_color_hex(0xE6E6E6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_top_date_lbl, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_top_panel = lv_obj_create(ui_scr1);
    lv_obj_set_width(ui_top_panel, 351);
    lv_obj_set_height(ui_top_panel, 50);
    lv_obj_set_x(ui_top_panel, 0);
    lv_obj_set_y(ui_top_panel, -150);
    lv_obj_set_align(ui_top_panel, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_top_panel, LV_OBJ_FLAG_HIDDEN);       /// Flags
    lv_obj_clear_flag(ui_top_panel, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_top_panel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_top_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_top_panel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_top_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_top_panel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_top_panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_top_panel, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_top_panel, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dummy_arc = lv_arc_create(ui_scr1);
    lv_obj_set_width(ui_dummy_arc, 150);
    lv_obj_set_height(ui_dummy_arc, 150);
    lv_obj_set_x(ui_dummy_arc, 99);
    lv_obj_set_y(ui_dummy_arc, -14);
    lv_obj_set_align(ui_dummy_arc, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_dummy_arc,
            LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE
                    | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC
                    | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN); /// Flags
    lv_arc_set_value(ui_dummy_arc, 50);
    lv_arc_set_bg_angles(ui_dummy_arc, 230, 310);
    lv_obj_set_style_arc_color(ui_dummy_arc, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_dummy_arc, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_dummy_arc, 7, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_dummy_arc, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_dummy_arc, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(ui_dummy_arc, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_dummy_arc, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_dummy_arc, 3, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_dummy_arc, lv_color_hex(0x000000), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_dummy_arc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_fuel_green_arc = lv_arc_create(ui_dummy_arc);
    lv_obj_set_width(ui_fuel_green_arc, 150);
    lv_obj_set_height(ui_fuel_green_arc, 150);
    lv_obj_set_align(ui_fuel_green_arc, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_fuel_green_arc,
            LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE
                    | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC
                    | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN); /// Flags
    lv_arc_set_value(ui_fuel_green_arc, 100);
    lv_arc_set_bg_angles(ui_fuel_green_arc, 230, 310);
    lv_obj_set_style_arc_color(ui_fuel_green_arc, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_fuel_green_arc, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_fuel_green_arc, 7, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_fuel_green_arc, lv_color_hex(0xFF0000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_fuel_green_arc, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(ui_fuel_green_arc, lv_color_hex(0x00FF64), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_fuel_green_arc, 100, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_fuel_green_arc, 7, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_fuel_green_arc, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_fuel_green_arc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_fuel_orange_arc = lv_arc_create(ui_dummy_arc);
    lv_obj_set_width(ui_fuel_orange_arc, 150);
    lv_obj_set_height(ui_fuel_orange_arc, 150);
    lv_obj_set_align(ui_fuel_orange_arc, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_fuel_orange_arc,
            LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE
                    | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC
                    | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN); /// Flags
    lv_arc_set_value(ui_fuel_orange_arc, 50);
    lv_arc_set_bg_angles(ui_fuel_orange_arc, 230, 310);
    lv_obj_set_style_arc_color(ui_fuel_orange_arc, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_fuel_orange_arc, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_fuel_orange_arc, 7, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_fuel_orange_arc, lv_color_hex(0xFF0000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_fuel_orange_arc, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(ui_fuel_orange_arc, lv_color_hex(0xFFAD00), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_fuel_orange_arc, 100, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_fuel_orange_arc, 7, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_fuel_orange_arc, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_fuel_orange_arc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_fuel_red_arc = lv_arc_create(ui_dummy_arc);
    lv_obj_set_width(ui_fuel_red_arc, 150);
    lv_obj_set_height(ui_fuel_red_arc, 150);
    lv_obj_set_align(ui_fuel_red_arc, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_fuel_red_arc,
            LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE
                    | LV_OBJ_FLAG_SNAPPABLE); /// Flags
    lv_arc_set_value(ui_fuel_red_arc, 15);
    lv_arc_set_bg_angles(ui_fuel_red_arc, 230, 310);
    lv_obj_set_style_arc_color(ui_fuel_red_arc, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_fuel_red_arc, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_fuel_red_arc, 7, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_fuel_red_arc, lv_color_hex(0xFF0000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_fuel_red_arc, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(ui_fuel_red_arc, lv_color_hex(0xFF0000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_fuel_red_arc, 100, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_fuel_red_arc, 7, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_fuel_red_arc, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_fuel_red_arc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_fuel_indicator_arc1 = lv_arc_create(ui_dummy_arc);
    lv_obj_set_width(ui_fuel_indicator_arc1, 150);
    lv_obj_set_height(ui_fuel_indicator_arc1, 150);
    lv_obj_set_align(ui_fuel_indicator_arc1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_fuel_indicator_arc1,
            LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE
                    | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC
                    | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN); /// Flags
    lv_arc_set_value(ui_fuel_indicator_arc1, 50);
    lv_arc_set_bg_angles(ui_fuel_indicator_arc1, 229, 311);
    lv_obj_set_style_arc_color(ui_fuel_indicator_arc1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_fuel_indicator_arc1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_fuel_indicator_arc1, 7, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_fuel_indicator_arc1, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_fuel_indicator_arc1, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(ui_fuel_indicator_arc1, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_fuel_indicator_arc1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_fuel_indicator_arc1, 3, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_fuel_indicator_arc1, lv_color_hex(0x000000), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_fuel_indicator_arc1, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_fuel_icon = lv_img_create(ui_scr1);
    lv_img_set_src(ui_fuel_icon, &ui_img_474709716);
    lv_obj_set_width(ui_fuel_icon, LV_SIZE_CONTENT);  /// 50
    lv_obj_set_height(ui_fuel_icon, LV_SIZE_CONTENT); /// 50
    lv_obj_set_x(ui_fuel_icon, 100);
    lv_obj_set_y(ui_fuel_icon, -70);
    lv_obj_set_align(ui_fuel_icon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_fuel_icon, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    lv_obj_clear_flag(ui_fuel_icon, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_img_set_zoom(ui_fuel_icon, 90);

    ui_fuel_max_lbl = lv_label_create(ui_scr1);
    lv_obj_set_width(ui_fuel_max_lbl, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_fuel_max_lbl, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_fuel_max_lbl, 143);
    lv_obj_set_y(ui_fuel_max_lbl, -58);
    lv_obj_set_align(ui_fuel_max_lbl, LV_ALIGN_CENTER);
    lv_label_set_text(ui_fuel_max_lbl, "60L");
    lv_obj_set_style_text_color(ui_fuel_max_lbl, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_fuel_max_lbl, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_fuel_max_lbl, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_temperature_img = lv_img_create(ui_scr1);
    lv_img_set_src(ui_temperature_img, &ui_img_temper_png);
    lv_obj_set_width(ui_temperature_img, LV_SIZE_CONTENT);  /// 16
    lv_obj_set_height(ui_temperature_img, LV_SIZE_CONTENT); /// 16
    lv_obj_set_x(ui_temperature_img, -90);
    lv_obj_set_y(ui_temperature_img, -110);
    lv_obj_set_align(ui_temperature_img, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_temperature_img, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    lv_obj_clear_flag(ui_temperature_img, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_top_temp_lbl = lv_label_create(ui_scr1);
    lv_obj_set_width(ui_top_temp_lbl, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_top_temp_lbl, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_top_temp_lbl, -65);
    lv_obj_set_y(ui_top_temp_lbl, -110);
    lv_obj_set_align(ui_top_temp_lbl, LV_ALIGN_CENTER);
    lv_label_set_text(ui_top_temp_lbl, "19°C");
    lv_obj_set_style_text_color(ui_top_temp_lbl, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_top_temp_lbl, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_humid_img = lv_img_create(ui_scr1);
    lv_img_set_src(ui_humid_img, &ui_img_weather_1_png);
    lv_obj_set_width(ui_humid_img, LV_SIZE_CONTENT);  /// 16
    lv_obj_set_height(ui_humid_img, LV_SIZE_CONTENT); /// 22
    lv_obj_set_x(ui_humid_img, -30);
    lv_obj_set_y(ui_humid_img, -110);
    lv_obj_set_align(ui_humid_img, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_humid_img, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    lv_obj_clear_flag(ui_humid_img, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_img_set_zoom(ui_humid_img, 190);

    ui_Label3 = lv_label_create(ui_scr1);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_Label3, -3);
    lv_obj_set_y(ui_Label3, -111);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "32%");
    lv_obj_set_style_text_color(ui_Label3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_setting_btn = lv_btn_create(ui_scr1);
    lv_obj_set_width(ui_setting_btn, 35);
    lv_obj_set_height(ui_setting_btn, 35);
    lv_obj_set_x(ui_setting_btn, -135);
    lv_obj_set_y(ui_setting_btn, -99);
    lv_obj_set_align(ui_setting_btn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_setting_btn, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
    lv_obj_clear_flag(ui_setting_btn, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
    lv_obj_set_style_bg_color(ui_setting_btn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_setting_btn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_setting_btn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_setting_btn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_settings_img = lv_img_create(ui_setting_btn);
    lv_img_set_src(ui_settings_img, &ui_img_settings_png);
    lv_obj_set_width(ui_settings_img, LV_SIZE_CONTENT);  /// 32
    lv_obj_set_height(ui_settings_img, LV_SIZE_CONTENT); /// 32
    lv_obj_set_x(ui_settings_img, -5);
    lv_obj_set_y(ui_settings_img, -7);
    lv_obj_set_align(ui_settings_img, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_settings_img, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    lv_obj_clear_flag(ui_settings_img, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_img_set_zoom(ui_settings_img, 180);

    lv_obj_add_event_cb(ui_gesture_panel_1, ui_event_gesture_panel_1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_gesture_panel_2, ui_event_gesture_panel_2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_gesture_panel_3, ui_event_gesture_panel_3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_gesture_panel_5, ui_event_gesture_panel_5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_gesture_panel_4, ui_event_gesture_panel_4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_scr1, ui_event_scr1, LV_EVENT_ALL, NULL);
}
