// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: esp32_gui

#include "../ui.h"

void ui_scr1_screen_init(void) {
    ui_scr1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_scr1, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_scr1, lv_color_hex(0x191919), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_scr1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_speed_panel = lv_obj_create(ui_scr1);
    lv_obj_set_width(ui_speed_panel, 100);
    lv_obj_set_height(ui_speed_panel, 190);
    lv_obj_set_x(ui_speed_panel, -10);
    lv_obj_set_y(ui_speed_panel, 0);
    lv_obj_set_align(ui_speed_panel, LV_ALIGN_RIGHT_MID);
    lv_obj_clear_flag(ui_speed_panel, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_radius(ui_speed_panel, 90, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_speed_panel, lv_color_hex(0x1A1A1A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_speed_panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_speed_panel, lv_color_hex(0x1A1A1A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_speed_panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_speed_panel, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_speed_panel, lv_color_hex(0x00FF64), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_speed_panel, 140, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_speed_panel, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_speed_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_speed_bar = lv_bar_create(ui_speed_panel);
    lv_bar_set_range(ui_speed_bar, 0, 150);
    lv_obj_set_width(ui_speed_bar, 90);
    lv_obj_set_height(ui_speed_bar, 180);
    lv_obj_set_align(ui_speed_bar, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_speed_bar, lv_color_hex(0x333333), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_speed_bar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_speed_bar, lv_color_hex(0x00FF64), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_speed_bar, 140, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_speed_num_lbl = lv_label_create(ui_speed_bar);
    lv_obj_set_height(ui_speed_num_lbl, 65);
    lv_obj_set_width(ui_speed_num_lbl, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_speed_num_lbl, LV_ALIGN_CENTER);
    lv_label_set_text(ui_speed_num_lbl, "0");
    lv_obj_set_style_text_color(ui_speed_num_lbl, lv_color_hex(0xE6E6E6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_speed_num_lbl, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_speed_num_lbl, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_km_h_lbl = lv_label_create(ui_speed_num_lbl);
    lv_obj_set_width(ui_km_h_lbl, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_km_h_lbl, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_km_h_lbl, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_km_h_lbl, "km/h");
    lv_obj_set_style_text_font(ui_km_h_lbl, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_gesture_panel_1 = lv_obj_create(ui_scr1);
    lv_obj_set_width(ui_gesture_panel_1, 337);
    lv_obj_set_height(ui_gesture_panel_1, 191);
    lv_obj_set_x(ui_gesture_panel_1, 1);
    lv_obj_set_y(ui_gesture_panel_1, 0);
    lv_obj_set_align(ui_gesture_panel_1, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_gesture_panel_1, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_IGNORE_LAYOUT); /// Flags
    lv_obj_clear_flag(ui_gesture_panel_1,
            LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SCROLL_ELASTIC
                    | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN); /// Flags
    lv_obj_set_style_bg_color(ui_gesture_panel_1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_gesture_panel_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_gesture_panel_1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_gesture_panel_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_scrolldots = lv_obj_create(ui_gesture_panel_1);
    lv_obj_set_width(ui_scrolldots, 77);
    lv_obj_set_height(ui_scrolldots, 30);
    lv_obj_set_x(ui_scrolldots, 65);
    lv_obj_set_y(ui_scrolldots, -15);
    lv_obj_set_align(ui_scrolldots, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_clear_flag(ui_scrolldots,
            LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE
                    | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC
                    | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN); /// Flags
    lv_obj_set_scrollbar_mode(ui_scrolldots, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_bg_color(ui_scrolldots, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_scrolldots, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_scrolldots, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_scrolldots, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_scrolldot_1 = lv_obj_create(ui_scrolldots);
    lv_obj_set_width(ui_scrolldot_1, 5);
    lv_obj_set_height(ui_scrolldot_1, 5);
    lv_obj_set_align(ui_scrolldot_1, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_scrolldot_1,
            LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE
                    | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC
                    | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN); /// Flags
    lv_obj_set_style_bg_color(ui_scrolldot_1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_scrolldot_1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_scrolldot_1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_scrolldot_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_scrolldot_1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_scrolldot_1, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_color(ui_scrolldot_1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_scrolldot_1, 0, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_scrolldot_2 = lv_obj_create(ui_scrolldots);
    lv_obj_set_width(ui_scrolldot_2, 5);
    lv_obj_set_height(ui_scrolldot_2, 5);
    lv_obj_set_x(ui_scrolldot_2, 15);
    lv_obj_set_y(ui_scrolldot_2, 0);
    lv_obj_set_align(ui_scrolldot_2, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_scrolldot_2,
            LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE
                    | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC
                    | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN); /// Flags
    lv_obj_set_style_bg_color(ui_scrolldot_2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_scrolldot_2, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_scrolldot_2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_scrolldot_2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_scrolldot_2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_scrolldot_2, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_color(ui_scrolldot_2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_scrolldot_2, 0, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_scrolldot_3 = lv_obj_create(ui_scrolldots);
    lv_obj_set_width(ui_scrolldot_3, 5);
    lv_obj_set_height(ui_scrolldot_3, 5);
    lv_obj_set_x(ui_scrolldot_3, 30);
    lv_obj_set_y(ui_scrolldot_3, 0);
    lv_obj_set_align(ui_scrolldot_3, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_scrolldot_3,
            LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE
                    | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC
                    | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN); /// Flags
    lv_obj_set_style_bg_color(ui_scrolldot_3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_scrolldot_3, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_scrolldot_3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_scrolldot_3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_scrolldot_3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_scrolldot_3, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_color(ui_scrolldot_3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_scrolldot_3, 0, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_scrolldot_4 = lv_obj_create(ui_scrolldots);
    lv_obj_set_width(ui_scrolldot_4, 5);
    lv_obj_set_height(ui_scrolldot_4, 5);
    lv_obj_set_x(ui_scrolldot_4, 45);
    lv_obj_set_y(ui_scrolldot_4, 0);
    lv_obj_set_align(ui_scrolldot_4, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_scrolldot_4,
            LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE
                    | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC
                    | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN); /// Flags
    lv_obj_set_style_bg_color(ui_scrolldot_4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_scrolldot_4, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_scrolldot_4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_scrolldot_4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_scrolldot_4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_scrolldot_4, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_color(ui_scrolldot_4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_scrolldot_4, 0, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_time_lbl = lv_label_create(ui_gesture_panel_1);
    lv_obj_set_height(ui_time_lbl, 60);
    lv_obj_set_width(ui_time_lbl, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_time_lbl, 60);
    lv_obj_set_y(ui_time_lbl, -70);
    lv_obj_set_align(ui_time_lbl, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_time_lbl, "16:35");
    lv_obj_set_style_text_color(ui_time_lbl, lv_color_hex(0xCCCCCC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_time_lbl, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_time_lbl, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_date_lbl = lv_label_create(ui_time_lbl);
    lv_obj_set_width(ui_date_lbl, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_date_lbl, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_date_lbl, 0);
    lv_obj_set_y(ui_date_lbl, -10);
    lv_obj_set_align(ui_date_lbl, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_date_lbl, "Sat, 5 Apr");
    lv_obj_set_style_text_font(ui_date_lbl, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_gesture_panel_2 = lv_obj_create(ui_scr1);
    lv_obj_set_width(ui_gesture_panel_2, 337);
    lv_obj_set_height(ui_gesture_panel_2, 191);
    lv_obj_set_x(ui_gesture_panel_2, 1);
    lv_obj_set_y(ui_gesture_panel_2, 0);
    lv_obj_set_align(ui_gesture_panel_2, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_gesture_panel_2, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_IGNORE_LAYOUT); /// Flags
    lv_obj_clear_flag(ui_gesture_panel_2,
            LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SCROLL_ELASTIC
                    | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN); /// Flags
    lv_obj_set_style_bg_color(ui_gesture_panel_2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_gesture_panel_2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_gesture_panel_2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_gesture_panel_2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_scrolldots1 = lv_obj_create(ui_gesture_panel_2);
    lv_obj_set_width(ui_scrolldots1, 77);
    lv_obj_set_height(ui_scrolldots1, 30);
    lv_obj_set_x(ui_scrolldots1, 40);
    lv_obj_set_y(ui_scrolldots1, -15);
    lv_obj_set_align(ui_scrolldots1, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_clear_flag(ui_scrolldots1,
            LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE
                    | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC
                    | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN); /// Flags
    lv_obj_set_scrollbar_mode(ui_scrolldots1, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_bg_color(ui_scrolldots1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_scrolldots1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_scrolldots1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_scrolldots1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_scrolldot_5 = lv_obj_create(ui_scrolldots1);
    lv_obj_set_width(ui_scrolldot_5, 5);
    lv_obj_set_height(ui_scrolldot_5, 5);
    lv_obj_set_align(ui_scrolldot_5, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_scrolldot_5,
            LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE
                    | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC
                    | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN); /// Flags
    lv_obj_set_style_bg_color(ui_scrolldot_5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_scrolldot_5, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_scrolldot_5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_scrolldot_5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_scrolldot_5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_scrolldot_5, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_color(ui_scrolldot_5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_scrolldot_5, 0, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_scrolldot_6 = lv_obj_create(ui_scrolldots1);
    lv_obj_set_width(ui_scrolldot_6, 5);
    lv_obj_set_height(ui_scrolldot_6, 5);
    lv_obj_set_x(ui_scrolldot_6, 15);
    lv_obj_set_y(ui_scrolldot_6, 0);
    lv_obj_set_align(ui_scrolldot_6, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_scrolldot_6,
            LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE
                    | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC
                    | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN); /// Flags
    lv_obj_set_style_bg_color(ui_scrolldot_6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_scrolldot_6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_scrolldot_6, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_scrolldot_6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_scrolldot_6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_scrolldot_6, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_color(ui_scrolldot_6, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_scrolldot_6, 0, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_scrolldot_7 = lv_obj_create(ui_scrolldots1);
    lv_obj_set_width(ui_scrolldot_7, 5);
    lv_obj_set_height(ui_scrolldot_7, 5);
    lv_obj_set_x(ui_scrolldot_7, 30);
    lv_obj_set_y(ui_scrolldot_7, 0);
    lv_obj_set_align(ui_scrolldot_7, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_scrolldot_7,
            LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE
                    | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC
                    | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN); /// Flags
    lv_obj_set_style_bg_color(ui_scrolldot_7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_scrolldot_7, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_scrolldot_7, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_scrolldot_7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_scrolldot_7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_scrolldot_7, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_color(ui_scrolldot_7, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_scrolldot_7, 0, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_scrolldot_8 = lv_obj_create(ui_scrolldots1);
    lv_obj_set_width(ui_scrolldot_8, 5);
    lv_obj_set_height(ui_scrolldot_8, 5);
    lv_obj_set_x(ui_scrolldot_8, 45);
    lv_obj_set_y(ui_scrolldot_8, 0);
    lv_obj_set_align(ui_scrolldot_8, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_scrolldot_8,
            LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE
                    | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC
                    | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN); /// Flags
    lv_obj_set_style_bg_color(ui_scrolldot_8, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_scrolldot_8, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_scrolldot_8, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_scrolldot_8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_scrolldot_8, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_scrolldot_8, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_color(ui_scrolldot_8, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_scrolldot_8, 0, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_gesture_panel_3 = lv_obj_create(ui_scr1);
    lv_obj_set_width(ui_gesture_panel_3, 337);
    lv_obj_set_height(ui_gesture_panel_3, 191);
    lv_obj_set_x(ui_gesture_panel_3, 1);
    lv_obj_set_y(ui_gesture_panel_3, 0);
    lv_obj_set_align(ui_gesture_panel_3, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_gesture_panel_3, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_IGNORE_LAYOUT); /// Flags
    lv_obj_clear_flag(ui_gesture_panel_3,
            LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SCROLL_ELASTIC
                    | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN); /// Flags
    lv_obj_set_style_bg_color(ui_gesture_panel_3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_gesture_panel_3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_gesture_panel_3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_gesture_panel_3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_scrolldots2 = lv_obj_create(ui_gesture_panel_3);
    lv_obj_set_width(ui_scrolldots2, 77);
    lv_obj_set_height(ui_scrolldots2, 30);
    lv_obj_set_x(ui_scrolldots2, 40);
    lv_obj_set_y(ui_scrolldots2, -15);
    lv_obj_set_align(ui_scrolldots2, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_clear_flag(ui_scrolldots2,
            LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE
                    | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC
                    | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN); /// Flags
    lv_obj_set_scrollbar_mode(ui_scrolldots2, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_bg_color(ui_scrolldots2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_scrolldots2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_scrolldots2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_scrolldots2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_scrolldot_9 = lv_obj_create(ui_scrolldots2);
    lv_obj_set_width(ui_scrolldot_9, 5);
    lv_obj_set_height(ui_scrolldot_9, 5);
    lv_obj_set_align(ui_scrolldot_9, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_scrolldot_9,
            LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE
                    | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC
                    | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN); /// Flags
    lv_obj_set_style_bg_color(ui_scrolldot_9, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_scrolldot_9, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_scrolldot_9, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_scrolldot_9, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_scrolldot_9, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_scrolldot_9, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_color(ui_scrolldot_9, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_scrolldot_9, 0, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_scrolldot_10 = lv_obj_create(ui_scrolldots2);
    lv_obj_set_width(ui_scrolldot_10, 5);
    lv_obj_set_height(ui_scrolldot_10, 5);
    lv_obj_set_x(ui_scrolldot_10, 15);
    lv_obj_set_y(ui_scrolldot_10, 0);
    lv_obj_set_align(ui_scrolldot_10, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_scrolldot_10,
            LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE
                    | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC
                    | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN); /// Flags
    lv_obj_set_style_bg_color(ui_scrolldot_10, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_scrolldot_10, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_scrolldot_10, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_scrolldot_10, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_scrolldot_10, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_scrolldot_10, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_color(ui_scrolldot_10, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_scrolldot_10, 0, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_scrolldot_11 = lv_obj_create(ui_scrolldots2);
    lv_obj_set_width(ui_scrolldot_11, 5);
    lv_obj_set_height(ui_scrolldot_11, 5);
    lv_obj_set_x(ui_scrolldot_11, 30);
    lv_obj_set_y(ui_scrolldot_11, 0);
    lv_obj_set_align(ui_scrolldot_11, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_scrolldot_11,
            LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE
                    | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC
                    | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN); /// Flags
    lv_obj_set_style_bg_color(ui_scrolldot_11, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_scrolldot_11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_scrolldot_11, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_scrolldot_11, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_scrolldot_11, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_scrolldot_11, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_color(ui_scrolldot_11, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_scrolldot_11, 0, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_scrolldot_12 = lv_obj_create(ui_scrolldots2);
    lv_obj_set_width(ui_scrolldot_12, 5);
    lv_obj_set_height(ui_scrolldot_12, 5);
    lv_obj_set_x(ui_scrolldot_12, 45);
    lv_obj_set_y(ui_scrolldot_12, 0);
    lv_obj_set_align(ui_scrolldot_12, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_scrolldot_12,
            LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE
                    | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC
                    | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN); /// Flags
    lv_obj_set_style_bg_color(ui_scrolldot_12, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_scrolldot_12, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_scrolldot_12, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_scrolldot_12, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_scrolldot_12, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_scrolldot_12, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_color(ui_scrolldot_12, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_scrolldot_12, 0, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_gesture_panel_4 = lv_obj_create(ui_scr1);
    lv_obj_set_width(ui_gesture_panel_4, 337);
    lv_obj_set_height(ui_gesture_panel_4, 191);
    lv_obj_set_x(ui_gesture_panel_4, 1);
    lv_obj_set_y(ui_gesture_panel_4, 0);
    lv_obj_set_align(ui_gesture_panel_4, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_gesture_panel_4, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_IGNORE_LAYOUT); /// Flags
    lv_obj_clear_flag(ui_gesture_panel_4,
            LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SCROLL_ELASTIC
                    | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN); /// Flags
    lv_obj_set_style_bg_color(ui_gesture_panel_4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_gesture_panel_4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_gesture_panel_4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_gesture_panel_4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_scrolldots3 = lv_obj_create(ui_gesture_panel_4);
    lv_obj_set_width(ui_scrolldots3, 77);
    lv_obj_set_height(ui_scrolldots3, 30);
    lv_obj_set_x(ui_scrolldots3, 40);
    lv_obj_set_y(ui_scrolldots3, -15);
    lv_obj_set_align(ui_scrolldots3, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_clear_flag(ui_scrolldots3,
            LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE
                    | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC
                    | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN); /// Flags
    lv_obj_set_scrollbar_mode(ui_scrolldots3, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_bg_color(ui_scrolldots3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_scrolldots3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_scrolldots3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_scrolldots3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_scrolldot_13 = lv_obj_create(ui_scrolldots3);
    lv_obj_set_width(ui_scrolldot_13, 5);
    lv_obj_set_height(ui_scrolldot_13, 5);
    lv_obj_set_align(ui_scrolldot_13, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_scrolldot_13,
            LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE
                    | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC
                    | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN); /// Flags
    lv_obj_set_style_bg_color(ui_scrolldot_13, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_scrolldot_13, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_scrolldot_13, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_scrolldot_13, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_scrolldot_13, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_scrolldot_13, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_color(ui_scrolldot_13, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_scrolldot_13, 0, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_scrolldot_14 = lv_obj_create(ui_scrolldots3);
    lv_obj_set_width(ui_scrolldot_14, 5);
    lv_obj_set_height(ui_scrolldot_14, 5);
    lv_obj_set_x(ui_scrolldot_14, 15);
    lv_obj_set_y(ui_scrolldot_14, 0);
    lv_obj_set_align(ui_scrolldot_14, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_scrolldot_14,
            LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE
                    | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC
                    | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN); /// Flags
    lv_obj_set_style_bg_color(ui_scrolldot_14, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_scrolldot_14, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_scrolldot_14, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_scrolldot_14, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_scrolldot_14, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_scrolldot_14, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_color(ui_scrolldot_14, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_scrolldot_14, 0, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_scrolldot_15 = lv_obj_create(ui_scrolldots3);
    lv_obj_set_width(ui_scrolldot_15, 5);
    lv_obj_set_height(ui_scrolldot_15, 5);
    lv_obj_set_x(ui_scrolldot_15, 30);
    lv_obj_set_y(ui_scrolldot_15, 0);
    lv_obj_set_align(ui_scrolldot_15, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_scrolldot_15,
            LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE
                    | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC
                    | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN); /// Flags
    lv_obj_set_style_bg_color(ui_scrolldot_15, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_scrolldot_15, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_scrolldot_15, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_scrolldot_15, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_scrolldot_15, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_scrolldot_15, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_color(ui_scrolldot_15, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_scrolldot_15, 0, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_scrolldot_16 = lv_obj_create(ui_scrolldots3);
    lv_obj_set_width(ui_scrolldot_16, 5);
    lv_obj_set_height(ui_scrolldot_16, 5);
    lv_obj_set_x(ui_scrolldot_16, 45);
    lv_obj_set_y(ui_scrolldot_16, 0);
    lv_obj_set_align(ui_scrolldot_16, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_scrolldot_16,
            LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE
                    | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC
                    | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN); /// Flags
    lv_obj_set_style_bg_color(ui_scrolldot_16, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_scrolldot_16, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_scrolldot_16, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_scrolldot_16, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_scrolldot_16, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_scrolldot_16, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_color(ui_scrolldot_16, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_scrolldot_16, 0, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_top_panel = lv_obj_create(ui_scr1);
    lv_obj_set_width(ui_top_panel, 350);
    lv_obj_set_height(ui_top_panel, 50);
    lv_obj_set_x(ui_top_panel, -121);
    lv_obj_set_y(ui_top_panel, -119);
    lv_obj_set_align(ui_top_panel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_top_panel, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_radius(ui_top_panel, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_top_panel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_top_panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_top_panel, lv_color_hex(0x1A1A1A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_top_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_top_panel, 250, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_top_panel, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_top_panel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_top_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_gesture_panel_1, ui_event_gesture_panel_1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_gesture_panel_2, ui_event_gesture_panel_2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_gesture_panel_3, ui_event_gesture_panel_3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_gesture_panel_4, ui_event_gesture_panel_4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_scr1, ui_event_scr1, LV_EVENT_ALL, NULL);
}
